on:
  pull_request:
    branches: ["main"]

jobs:
  static-checks:
    name: 'Static checks'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@v6
        with:
          token: ${{ secrets.ESCORIA_DEPLOYMENT_TOKEN }}
          fetch-depth: 0

      - name: 'Get changed GDScript files'
        id: changed-gd-files
        uses: step-security/changed-files@60967b822d3001fa82242f8d6b4ed46bc3600a68 # v47.0.1
        with:
          files: |
            **/*.gd

      - name: 'Install GDScript Toolkit'
        if: steps.changed-gd-files.outputs.any_changed == 'true'
        uses: Scony/godot-gdscript-toolkit@b7a4935fc6483d51837f7080598dad456f4f7645 # v4.5.0

      - name: 'Run static checks on changed GDScript files'
        if: steps.changed-gd-files.outputs.any_changed == 'true'
        run: |
          gdlint ${{ steps.changed-gd-files.outputs.all_changed_files }}
